version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

  web:
    build: .
    command: gunicorn -k eventlet -w 4 -b 0.0.0.0:8080 api:app
    environment:
      - FLASK_ENV=production
    networks:
      - my_network

  locust:
    build: .
    command: locust --host=http://nginx
    ports:
      - "8089:8089"
    depends_on:
      - web
      - nginx
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
