name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # ajuste para o seu branch de produção

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: flaskOmnichat

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract client_email field
      id: extract_field
      run: echo "CLIENT_EMAIL=$(echo $GCP_SA_KEY | jq -r '.client_email')" >> $GITHUB_ENV
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    # Adicionando a autenticação com Workload Identity Provider
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        service_account: ${{ env.CLIENT_EMAIL }}

    - name: Build Docker Image
      run: | 
        docker build -t ${{ env.IMAGE_NAME }} .
        docker tag ${{ env.IMAGE_NAME }} gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

    - name: Push Docker Image to Google Container Registry
      run: |
        gcloud auth configure-docker
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.IMAGE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }} \
          --platform managed \
          --region us-central1
